import { useEffect, useMemo, useState } from 'react';
import type { ChangeEvent, ReactNode } from 'react';
import { BookOpen, Check, Code2, Download, FileCode2, Gauge, Leaf, LineChart, Loader2, Menu, Play, RefreshCw, Settings, ShieldCheck, Sparkles, Upload, X, Zap } from 'lucide-react';

type Alternative = { id: string; title: string; description: string; complexity: string; expectedRuntimeChange: string; expectedMemoryChange: string; simplicity: string; readability: string; maintainability: string; portability: string; projectedEnergyChange: string; projectedCarbonChange: string; code?: string };
type Result = { ok: boolean; submission: { language: string; detectionConfidence: string; bytes: number; lines: number }; analysis: { score: number; complexity: { time: string; space: string; basis: string }; findings: { severity: string; title: string; detail: string }[]; alternatives: Alternative[] }; security: { score: number; findings: { severity: string; title: string; detail: string }[] }; compile: { status: string; stderr: string; } | null; execution: { status: string; wallTimeMs: number | null; cpuTimeMs: number | null; peakMemoryKb: number | null; stdout: string; stderr: string; measured: boolean; sandbox: string } | null; eco: { energyWh: number | null; carbonGrams: number | null; measured: boolean; basis: string; assumptions: { cpuPackageWatts: number; carbonIntensityGPerKwh: number } }; comparison: { delta: { runtimeMs: number | null; runtimePercent: number | null; peakMemoryKb: number | null; carbonGrams: number | null }; execution: Result['execution']; eco: Result['eco'] } | null; limits: { timeoutMs: number; memoryMb: number; processLimit: number }; benchmark: { iterationsRequested: number; strategy: string }; model: { note: string } };
type Coach = { provider: string; summary: string; recommendations: string[]; nextTests: string[]; risks?: string[] };

const samples: Record<string, { fileName: string; code: string }> = {
  javascript: { fileName: 'analysis.js', code: `function uniqueItems(items) {\n  const result = [];\n  for (let i = 0; i < items.length; i++) {\n    if (!result.includes(items[i])) result.push(items[i]);\n  }\n  return result;\n}\nconsole.log(uniqueItems(Array.from({ length: 1000 }, (_, i) => i % 400)).length);` },
  typescript: { fileName: 'analysis.ts', code: `function groupBy<T>(items: T[], key: keyof T) {\n  return items.reduce((groups, item) => {\n    const value = String(item[key]);\n    (groups[value] ??= []).push(item);\n    return groups;\n  }, {} as Record<string, T[]>);\n}\nconsole.log(groupBy([{id: 1}, {id: 1}, {id: 2}], 'id'));` },
  python: { fileName: 'analysis.py', code: `def latest(records):\n    out = {}\n    for record in records:\n        key = record["user_id"]\n        if key not in out or record["created_at"] > out[key]["created_at"]:\n            out[key] = record\n    return list(out.values())\nprint(latest([{"user_id": 1, "created_at": 2}, {"user_id": 1, "created_at": 3}]))` },
  c: { fileName: 'analysis.c', code: `#include <stdio.h>\nint main(void) {\n  long total = 0;\n  for (int i = 0; i < 500000; i++) total += i;\n  printf("%ld\\n", total);\n  return 0;\n}` },
  cpp: { fileName: 'analysis.cpp', code: `#include <iostream>\nint main() {\n  long long total = 0;\n  for (int i = 0; i < 500000; ++i) total += i;\n  std::cout << total << "\\n";\n}` },
  go: { fileName: 'analysis.go', code: `package main\nimport "fmt"\nfunc main() {\n  total := 0\n  for i := 0; i < 500000; i++ { total += i }\n  fmt.Println(total)\n}` },
};
const labels: Record<string, string> = { javascript: 'JavaScript', typescript: 'TypeScript', python: 'Python', c: 'C', cpp: 'C++', go: 'Go' };
const profiles = ['balanced', 'fast', 'memory', 'green', 'reliable', 'secure', 'scalable'];
function ms(v: number | null | undefined) { return v == null ? 'Unavailable' : `${v.toFixed(3)} ms`; }
function memory(v: number | null | undefined) { return v == null ? 'Unavailable' : v < 1024 ? `${v} KB` : `${(v / 1024).toFixed(2)} MB`; }
function energy(v: number | null | undefined) { return v == null ? 'Unavailable' : `${v.toFixed(6)} Wh`; }
function carbon(v: number | null | undefined) { return v == null ? 'Unavailable' : `${v.toFixed(6)} gCO₂e`; }

export default function AppReal() {
  const [page, setPage] = useState<'overview'|'analyzer'|'history'|'learn'|'settings'>('analyzer');
  const [language, setLanguage] = useState('javascript');
  const [code, setCode] = useState(samples.javascript.code);
  const [fileName, setFileName] = useState(samples.javascript.fileName);
  const [candidate, setCandidate] = useState('');
  const [profile, setProfile] = useState('balanced');
  const [iterations, setIterations] = useState(1);
  const [instruction, setInstruction] = useState('');
  const [result, setResult] = useState<Result | null>(null);
  const [coach, setCoach] = useState<Coach | null>(null);
  const [history, setHistory] = useState<Result[]>([]);
  const [loading, setLoading] = useState(false);
  const [coachLoading, setCoachLoading] = useState(false);
  const [error, setError] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const currentAlt = useMemo(() => result?.analysis.alternatives.find(a => a.id === candidate), [result, candidate]);

  useEffect(() => { try { const saved = localStorage.getItem('ecodev-history'); if (saved) setHistory(JSON.parse(saved).slice(0, 12)); } catch {} }, []);
  function saveHistory(next: Result) { const list = [next, ...history].slice(0, 12); setHistory(list); try { localStorage.setItem('ecodev-history', JSON.stringify(list)); } catch {} }
  function loadSample(lang: string) { const s = samples[lang] ?? samples.javascript; setLanguage(lang); setCode(s.code); setFileName(s.fileName); setCandidate(''); setResult(null); setCoach(null); setError(''); }
  async function analyze() {
    setLoading(true); setError(''); setCoach(null);
    try {
      const response = await fetch('/api/analyze', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ code, language, execute: true, benchmarkIterations: iterations, preferences: { profile, instruction }, ...(currentAlt?.code ? { compareCode: currentAlt.code, compareLanguage: language } : {}) }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Analysis failed');
      setResult(data); saveHistory(data);
    } catch (e) { setError(e instanceof Error ? e.message : 'Analysis failed'); } finally { setLoading(false); }
  }
  async function runCoach() {
    setCoachLoading(true); setError('');
    try { const response = await fetch('/api/coach', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({code, language, instruction}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Coach failed'); setCoach(data); }
    catch (e) { setError(e instanceof Error ? e.message : 'Coach failed'); } finally { setCoachLoading(false); }
  }
  async function downloadReport(format: 'markdown'|'json') {
    if (!result) return;
    const response = await fetch('/api/report', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({result, format}) });
    const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `ecodev-${Date.now()}.${format === 'markdown' ? 'md' : 'json'}`; a.click(); URL.revokeObjectURL(url);
  }
  function importFile(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; setFileName(file.name); const ext = file.name.split('.').pop()?.toLowerCase(); const detected = ext === 'ts' ? 'typescript' : ext === 'py' ? 'python' : ext === 'cpp' || ext === 'cc' || ext === 'cxx' ? 'cpp' : ext === 'c' ? 'c' : ext === 'go' ? 'go' : 'javascript'; setLanguage(detected); setCandidate(''); file.text().then(setCode).catch(() => setError('Could not read the selected file.')); }
  const nav = [['overview','Overview',Gauge],['analyzer','Analyzer',Code2],['history','History',LineChart],['learn','Learn',BookOpen],['settings','Settings',Settings]] as const;

  return <div className="min-h-[100dvh] bg-[#0d1b14] text-[#e7f0d6]">
    <aside className={`fixed inset-y-0 left-0 z-50 w-[250px] border-r border-[#294734] bg-[#10281b] p-5 transition-transform md:translate-x-0 ${mobileOpen?'translate-x-0':'-translate-x-full'}`}>
      <div className="mb-10 flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] bg-[#c6ed51] text-[#183d2a]"><Leaf size={19}/></span><b>EcoDev</b></div><button className="md:hidden" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>
      <div className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[0.17em] text-[#93aa96]">Workspace</div>
      <nav className="space-y-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setPage(id);setMobileOpen(false)}} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-[13px] font-semibold ${page===id?'bg-[#2c5b3d] text-white':'text-[#cfddc9] hover:bg-[#234c34]'}`}><Icon size={17}/><span>{label}</span>{id==='analyzer'&&<span className="ml-auto rounded bg-[#c6ed51]/15 px-1.5 py-0.5 font-mono text-[9px] text-[#c6ed51]">LIVE</span>}</button>)}</nav>
      <div className="mt-10 rounded-xl border border-[#31513b] bg-[#153320] p-4"><div className="mb-2 flex items-center gap-2 text-xs font-bold"><ShieldCheck size={15}/> Secure execution</div><p className="text-[11px] leading-5 text-[#a9bea9]">Execution is fail-closed unless Bubblewrap or Firejail is available. Static security checks run independently.</p></div>
    </aside>
    <div className="md:pl-[250px]">
      <header className="sticky top-0 z-40 flex items-center justify-between border-b border-[#243b2d] bg-[#0d1b14]/95 px-4 py-4 backdrop-blur md:px-8"><button className="md:hidden" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#86a18c]">Eco-efficient software engineering</p><h1 className="mt-1 text-lg font-extrabold">{page[0].toUpperCase()+page.slice(1)}</h1></div><div className="flex items-center gap-2 text-xs text-[#91a994]"><Zap size={15}/> measured when available</div></header>
      {page==='analyzer'&&<main className="mx-auto max-w-[1280px] p-4 md:p-8">
        <div className="mb-6"><h2 className="text-3xl font-extrabold tracking-tight">Analyze, execute, optimize, and verify.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#9fb4a0]">EcoDev combines static complexity, security checks, sandboxed execution, benchmark statistics, optimization alternatives, green-computing estimates, and an optional AI coach. Measurements are never presented as guesses.</p></div>
        <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
          <div className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5 shadow-xl">
            <div className="mb-4 grid gap-3 sm:grid-cols-[auto_1fr_auto_auto]"><select value={language} onChange={e=>loadSample(e.target.value)} className="rounded-lg border border-[#36533e] bg-[#142b1e] px-3 py-2 text-sm"><option value="javascript">JavaScript</option><option value="typescript">TypeScript</option><option value="python">Python</option><option value="c">C</option><option value="cpp">C++</option><option value="go">Go</option></select><input value={fileName} onChange={e=>setFileName(e.target.value)} className="rounded-lg border border-[#36533e] bg-[#142b1e] px-3 py-2 text-sm"/><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-[#36533e] px-3 py-2 text-xs font-bold"><Upload size={14}/> Import<input type="file" className="hidden" onChange={importFile}/></label><button onClick={()=>loadSample(language)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#36533e] px-3 py-2 text-xs font-bold"><RefreshCw size={14}/> Sample</button></div>
            <textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false} className="min-h-[390px] w-full resize-y rounded-xl border border-[#294432] bg-[#09150e] p-4 font-mono text-[13px] leading-6 text-[#d8e9cf] outline-none focus:border-[#78a84a]"/>
            <div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_auto_auto]"><select value={profile} onChange={e=>setProfile(e.target.value)} className="rounded-lg border border-[#36533e] bg-[#142b1e] px-3 py-2 text-sm">{profiles.map(p=><option key={p} value={p}>{p} profile</option>)}</select><select value={iterations} onChange={e=>setIterations(Number(e.target.value))} className="rounded-lg border border-[#36533e] bg-[#142b1e] px-3 py-2 text-sm"><option value={1}>1 run</option><option value={3}>3 runs</option><option value={5}>5 runs</option></select><button disabled={coachLoading} onClick={runCoach} className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#36533e] px-4 py-2.5 text-sm font-bold">{coachLoading?<Loader2 className="animate-spin" size={16}/>:<Sparkles size={16}/>} Coach</button><button disabled={loading} onClick={analyze} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#c6ed51] px-5 py-2.5 text-sm font-extrabold text-[#17301f] disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={16}/>:<Play size={16}/>} Analyze</button></div>
            <input value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Optimization goal, e.g. minimize memory without hurting runtime" className="mt-3 w-full rounded-lg border border-[#36533e] bg-[#142b1e] px-3 py-2 text-sm"/>
            {error&&<div className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-200">{error}</div>}
          </div>
          <div className="space-y-5">
            <div className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-[#8ea891]">Status</p><h3 className="mt-1 text-lg font-extrabold">{result ? 'Analysis complete' : 'Ready to analyze'}</h3></div><div className="rounded-lg bg-[#c6ed51]/10 p-2 text-[#c6ed51]"><Check size={18}/></div></div><div className="grid grid-cols-2 gap-3 text-xs"><div className="rounded-lg bg-[#142b1e] p-3"><span className="text-[#91a994]">Language</span><b className="mt-1 block">{result ? labels[result.submission.language] ?? result.submission.language : labels[language]}</b></div><div className="rounded-lg bg-[#142b1e] p-3"><span className="text-[#91a994]">Lines</span><b className="mt-1 block">{result?.submission.lines ?? code.split('\n').length}</b></div><div className="rounded-lg bg-[#142b1e] p-3"><span className="text-[#91a994]">Efficiency</span><b className="mt-1 block">{result ? `${result.analysis.score}/100` : '—'}</b></div><div className="rounded-lg bg-[#142b1e] p-3"><span className="text-[#91a994]">Security</span><b className="mt-1 block">{result ? `${result.security.score}/100` : '—'}</b></div></div></div>
            {result&&<>
              <div className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><h3 className="mb-3 text-sm font-extrabold">Runtime & eco metrics</h3><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-[#91a994]">Wall time</span><b className="mt-1 block">{ms(result.execution?.wallTimeMs)}</b></div><div><span className="text-[#91a994]">CPU time</span><b className="mt-1 block">{ms(result.execution?.cpuTimeMs)}</b></div><div><span className="text-[#91a994]">Peak memory</span><b className="mt-1 block">{memory(result.execution?.peakMemoryKb)}</b></div><div><span className="text-[#91a994]">Energy</span><b className="mt-1 block">{energy(result.eco.energyWh)}</b></div><div><span className="text-[#91a994]">Carbon</span><b className="mt-1 block">{carbon(result.eco.carbonGrams)}</b></div><div><span className="text-[#91a994]">Sandbox</span><b className="mt-1 block">{result.execution?.sandbox ?? 'static-only'}</b></div></div><p className="mt-3 text-[10px] leading-4 text-[#7f9682]">Energy and carbon are estimates derived from measured CPU time and configured assumptions, unless a provider reports direct telemetry.</p></div>
              <div className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><h3 className="mb-3 text-sm font-extrabold">Optimization alternatives</h3><div className="space-y-3">{result.analysis.alternatives.slice(0,5).map(a=><button key={a.id} onClick={()=>setCandidate(a.id)} className={`w-full rounded-lg border p-3 text-left ${candidate===a.id?'border-[#c6ed51] bg-[#c6ed51]/10':'border-[#31513b] bg-[#142b1e]'}`}><div className="flex items-center justify-between"><span className="text-sm font-bold">{a.title}</span><span className="text-[10px] text-[#91a994]">{a.complexity}</span></div><p className="mt-1 text-[11px] leading-5 text-[#9fb4a0]">{a.description}</p></button>)}</div>{currentAlt?.code&&<div className="mt-4 rounded-lg border border-[#31513b] bg-[#0b170f] p-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-wider text-[#8ea891]">Selected candidate</div><pre className="max-h-48 overflow-auto whitespace-pre-wrap font-mono text-[11px] leading-5 text-[#d8e9cf]">{currentAlt.code}</pre><p className="mt-2 text-[10px] text-[#8ea891]">Run Analyze again to benchmark the original code against this candidate.</p></div>}</div>
              <div className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-extrabold">Reports</h3><Download size={15}/></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>downloadReport('markdown')} className="rounded-lg border border-[#36533e] px-3 py-2 text-xs font-bold">Markdown</button><button onClick={()=>downloadReport('json')} className="rounded-lg border border-[#36533e] px-3 py-2 text-xs font-bold">JSON</button></div></div>
            </>}
          </div>
        </section>
      </main>}
      {page==='overview'&&<main className="mx-auto max-w-[1280px] p-4 md:p-8"><h2 className="text-3xl font-extrabold">EcoDev overview</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#9fb4a0]">A practical workspace for measuring runtime behavior, spotting algorithmic hotspots, reviewing security risks, and comparing greener implementation choices.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Analyze','Complexity + runtime + memory'],['Optimize','Trade-offs and candidate code'],['Verify','Benchmark and report']].map(([t,d])=><div key={t} className="rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><b>{t}</b><p className="mt-2 text-xs leading-5 text-[#91a994]">{d}</p></div>)}</div></main>}
      {page==='history'&&<main className="mx-auto max-w-[1280px] p-4 md:p-8"><h2 className="text-3xl font-extrabold">History</h2><div className="mt-6 space-y-3">{history.length?history.map((item,i)=><div key={i} className="rounded-xl border border-[#2b4634] bg-[#102318] p-4 text-xs"><div className="flex justify-between"><b>{labels[item.submission.language] ?? item.submission.language}</b><span className="text-[#91a994]">{item.submission.lines} lines</span></div><div className="mt-2 text-[#91a994]">Efficiency {item.analysis.score}/100 · Security {item.security.score}/100 · Runtime {ms(item.execution?.wallTimeMs)}</div></div>):<p className="text-sm text-[#91a994]">No saved analyses yet.</p>}</div></main>}
      {page==='learn'&&<main className="mx-auto max-w-[1000px] p-4 md:p-8"><h2 className="text-3xl font-extrabold">Learn</h2><div className="mt-6 rounded-2xl border border-[#2b4634] bg-[#102318] p-5"><h3 className="text-lg font-extrabold">What EcoDev measures</h3><div className="mt-3 space-y-3 text-sm leading-6 text-[#9fb4a0]"><p><b className="text-white">Static analysis:</b> heuristic complexity, hotspots, and security checks.</p><p><b className="text-white">Runtime measurement:</b> wall time, CPU time, and peak resident memory inside the configured sandbox.</p><p><b className="text-white">Green estimates:</b> CPU time multiplied by configured CPU package power, then carbon intensity.</p><p><b className="text-white">Optimization:</b> alternatives include hash-based lookup, sorting once, streaming/chunking, batching, and top-k patterns with trade-offs.</p></div></div></main>}
      {page==='settings'&&<main className="mx-auto max-w-[1000px] p-4 md:p-8"><h2 className="text-3xl font-extrabold">Settings</h2><div className="mt-6 rounded-2xl border border-[#2b4634] bg-[#102318] p-5 text-sm text-[#9fb4a0]">Runtime limits and energy assumptions are configured on the server through <code className="text-[#c6ed51]">ECODEV_*</code> environment variables. The UI never labels estimates as direct measurements.</div></main>}
    </div>
  </div>;
}
